#! /usr/bin/env ruby

enable_defaults! { ENV["RACK_ENV"] != "production" }

variable :RAILS_MAX_THREADS, :integer, default: 5
variable :WEB_CONCURRENCY, :integer, default: 2
variable :RAILS_MASTER_KEY, :string, default: "private"
variable :ORIGIN_ENCRYPTION_PRIVATE, :string, default: "private"
variable :ORIGIN_ENCRYPTION_SALT, :string, default: "salt"
variable :RAILS_SESSION_PRIVATE, :string, default: "private"
variable :ORIGIN_LOCATION, :string, default: "localhost:3000"
variable :WWW_LOCATION, :string, default: "localhost:3001"
variable :RAILS_EMAIL_FROM, :string, default: "noreply@localhost"

group :development do
  variable :PORT, :integer, default: 3000
end

group :production do
  variable :RACK_ENV, :string
  variable :RAILS_ENV, :string
  variable :REDIS_URL, :string
  variable :DATABASE_URL, :string
  variable :PGBOUNCER_POOL, :integer
  variable :RAILS_SERVE_STATIC_FILES, :string
  variable :RAILS_LOG_TO_STDOUT, :string
end
