ENCRYPTION_KEY_GENERATOR = ActiveSupport::KeyGenerator.new(ENVied.ORIGIN_ENCRYPTION_PRIVATE)
ENCRYPTION_KEY = ENCRYPTION_KEY_GENERATOR.generate_key(ENVied.ORIGIN_ENCRYPTION_SALT, 32)
ENCRYPTOR = ActiveSupport::MessageEncryptor.new(ENCRYPTION_KEY)
