{
 "title": "CPU Usage",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}
{
 "title": "CPU Quota",
 "panels": [
  {
   "title": "CPU Quota",
   "type": "table",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=\"$pod\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=\"$pod\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    }
   ]
  }
 ]
}
{
 "title": "Memory Usage",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}
{
 "title": "Memory Quota",
 "panels": [
  {
   "title": "Memory Quota",
   "type": "table",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\", container_name!=\"\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    }
   ]
  }
 ]
}
{
 "title": "CoreDNS",
 "description": "A dashboard for the CoreDNS DNS server.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "up{job=\"coredns\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests (total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_count_total{instance=~\"$instance\"}[5m])) by (proto)",
     "legendFormat": "{{proto}}"
    },
    {
     "expr": "sum(rate(coredns_dns_request_count_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Requests (by qtype)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_type_count_total{instance=~\"$instance\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests (by zone)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_count_total{instance=~\"$instance\"}[5m])) by (zone)",
     "legendFormat": "{{zone}}"
    },
    {
     "expr": "sum(rate(coredns_dns_request_count_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Requests (DO bit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_do_count_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "DO"
    },
    {
     "expr": "sum(rate(coredns_dns_request_count_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Requests (size, udp)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\",proto=\"udp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:99 "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\",proto=\"udp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\",proto=\"udp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:50"
    }
   ]
  },
  {
   "title": "Requests (size,tcp)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\",proto=\"tcp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:99 "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\",proto=\"tcp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\",proto=\"tcp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:50"
    }
   ]
  },
  {
   "title": "Responses (by rcode)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_response_rcode_count_total{instance=~\"$instance\"}[5m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Responses (duration)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le, job))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Responses (size, udp)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\",proto=\"udp\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{instance=\"$instance\",proto=\"udp\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\",proto=\"udp\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:50%"
    }
   ]
  },
  {
   "title": "Responses (size, tcp)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\",proto=\"tcp\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\",proto=\"tcp\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\",proto=\"tcp\"}[5m])) by (le, proto)) ",
     "legendFormat": "{{proto}}:50%"
    }
   ]
  },
  {
   "title": "Cache (size)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(coredns_cache_size{instance=~\"$instance\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache (hitrate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{instance=~\"$instance\"}[5m])) by (type)",
     "legendFormat": "hits:{{type}}"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{instance=~\"$instance\"}[5m])) by (type)",
     "legendFormat": "misses"
    }
   ]
  }
 ]
}
{
 "title": "CPU",
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_utilisation:avg1m{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "CPU Saturation (Load1)",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_saturation_load1:{node=\"$node\"}",
     "legendFormat": "Saturation"
    }
   ]
  }
 ]
}
{
 "title": "Memory",
 "panels": [
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_utilisation:{node=\"$node\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Memory Saturation (Swap I/O)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_swap_io_bytes:sum_rate{node=\"$node\"}",
     "legendFormat": "Swap IO"
    }
   ]
  }
 ]
}
{
 "title": "Disk",
 "panels": [
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_utilisation:avg_irate{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_saturation:avg_irate{node=\"$node\"}",
     "legendFormat": "Saturation"
    }
   ]
  }
 ]
}
{
 "title": "Net",
 "panels": [
  {
   "title": "Net Utilisation (Transmitted)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_utilisation:sum_irate{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Net Saturation (Dropped)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_saturation:sum_irate{node=\"$node\"}",
     "legendFormat": "Saturation"
    }
   ]
  }
 ]
}
{
 "title": "Disk",
 "panels": [
  {
   "title": "Disk Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_filesystem_usage:\n* on (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:{node=\"$node\"}\n",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}
{
 "title": "Row",
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{job=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$cluster\",grpc_type=\"unary\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$cluster\",grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{job=\"$cluster\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job=\"$cluster\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{job=\"$cluster\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job=\"$cluster\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "DB Size",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{job=\"$cluster\"}",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$cluster\"}",
     "legendFormat": "{{instance}} Resident Memory"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Client Traffic In",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{job=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{job=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{job=\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{job=\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic Out"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Raft Proposals",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{job=\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{job=\"$cluster\"})",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{job=\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{job=\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Day",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{job=\"$cluster\"}[1d])",
     "legendFormat": "{{instance}} Total Leader Elections Per Day"
    }
   ]
  }
 ]
}
{
 "title": "Headlines",
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "format": "percentunit",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Requests Commitment",
   "type": "singlestat",
   "format": "percentunit",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) / sum(node:node_num_cpu:sum)"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "singlestat",
   "format": "percentunit",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores) / sum(node:node_num_cpu:sum)"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "singlestat",
   "format": "percentunit",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemFreeCachedBuffers_bytes:sum) / sum(:node_memory_MemTotal_bytes:sum)"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "singlestat",
   "format": "percentunit",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) / sum(:node_memory_MemTotal_bytes:sum)"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "singlestat",
   "format": "percentunit",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes) / sum(:node_memory_MemTotal_bytes:sum)"
    }
   ]
  }
 ]
}
{
 "title": "CPU",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}
{
 "title": "CPU Quota",
 "panels": [
  {
   "title": "CPU Quota",
   "type": "table",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (namespace)"
    },
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate) by (namespace) / sum(kube_pod_container_resource_requests_cpu_cores) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores) by (namespace)"
    },
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate) by (namespace) / sum(kube_pod_container_resource_limits_cpu_cores) by (namespace)"
    }
   ]
  }
 ]
}
{
 "title": "Memory",
 "panels": [
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container_name!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}
{
 "title": "Memory Requests",
 "panels": [
  {
   "title": "Requests by Namespace",
   "type": "table",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container_name!=\"\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{container_name!=\"\"}) by (namespace) / sum(kube_pod_container_resource_requests_memory_bytes) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{container_name!=\"\"}) by (namespace) / sum(kube_pod_container_resource_limits_memory_bytes) by (namespace)"
    }
   ]
  }
 ]
}
{
 "title": "CPU",
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:cluster_cpu_utilisation:ratio",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  },
  {
   "title": "CPU Saturation (Load1)",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_saturation_load1: / scalar(sum(min(kube_pod_info) by (node)))",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  }
 ]
}
{
 "title": "Memory",
 "panels": [
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:cluster_memory_utilisation:ratio",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  },
  {
   "title": "Memory Saturation (Swap I/O)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_swap_io_bytes:sum_rate",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  }
 ]
}
{
 "title": "Disk",
 "panels": [
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_utilisation:avg_irate / scalar(:kube_pod_info_node_count:)",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_saturation:avg_irate / scalar(:kube_pod_info_node_count:)",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  }
 ]
}
{
 "title": "Network",
 "panels": [
  {
   "title": "Net Utilisation (Transmitted)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_utilisation:sum_irate",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  },
  {
   "title": "Net Saturation (Dropped)",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_saturation:sum_irate",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  }
 ]
}
{
 "title": "Storage",
 "panels": [
  {
   "title": "Disk Capacity",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(max(node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\"} - node_filesystem_avail_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\"}) by (device,pod,namespace)) by (pod,namespace)\n/ scalar(sum(max(node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\"}) by (device,pod,namespace)))\n* on (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:\n",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  }
 ]
}
{
 "title": "CPU Usage",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}
{
 "title": "CPU Quota",
 "panels": [
  {
   "title": "CPU Quota",
   "type": "table",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  }
 ]
}
{
 "title": "Memory Usage",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", container_name!=\"\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}
{
 "title": "Memory Quota",
 "panels": [
  {
   "title": "Memory Quota",
   "type": "table",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  }
 ]
}