require_relative("source/extensions/action_dispatch_http_headers_inspect")
require_relative("source/extensions/rails_console_account_access")
require_relative("source/extensions/pundit_not_authorized_error_message")
